### ISSUE TITLE
您好，请问一下，用你提供的在corpus下的语料直接训练会报错，请问是语料行数的问题吗？

### ISSUE THREAD

**Issue by Allen15rg** [EliasCai/idcard-ocr#1]
........................................

2019-08-27 20:22:56 Epoch 1/1000
2019-08-27 20:22:56 Exception in thread Thread-2:
2019-08-27 20:22:56 Traceback (most recent call last):
2019-08-27 20:22:56   File "/usr/local/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2019-08-27 20:22:56     self.run()
2019-08-27 20:22:56   File "/usr/local/anaconda3/lib/python3.6/threading.py", line 864, in run
2019-08-27 20:22:56     self._target(*self._args, **self._kwargs)
2019-08-27 20:22:56   File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
2019-08-27 20:22:56     generator_output = next(self._generator)
**2019-08-27 20:22:56 ValueError: generator already executing**
2019-08-27 20:22:56 
........................

2019-08-27 20:22:56 The number of corpus is 84
2019-08-27 20:22:56 Exception in thread Thread-1:
**2019-08-27 20:22:56 ValueError: Sample larger than population or is negative**

**Comment by Uncle-Justice** [comment]
same problem for me too
